teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: -1
      z: -1

    axis_angular:
      yaw: 0
      pitch: -1
      roll: -1

    scale_linear:
      x: 1.0
      y: 0.0
      z: 0.0

    scale_angular:
      yaw: 1.0
      pitch: 0.0
      roll: 0.0
    
    require_enable_button: false
    enable_button: -1
    enable_turbo_button: -1
